#!/usr/bin/env python3
"""Generate a self-contained procedural 6-DOF arm URDF (no external meshes)."""
import os

OUT = os.path.join(os.path.dirname(__file__), "..", "assets", "urdf", "demo_arm.urdf")

# name, parent, xyz, rpy, axis, type, lower, upper, effort, damping, visual-geom, visual-origin, size, mass
SEGMENTS = [
    ("shoulder_link", "base_link", (0, 0, 0.10), "cyl", (0, 0, 0.06), (0.055, 0.12), 2.0, "orange"),
    ("upper_arm_link", "shoulder_link", (0, 0, 0.12), "box", (0, 0, 0.15), (0.06, 0.06, 0.30), 2.5, "orange"),
    ("forearm_link", "upper_arm_link", (0, 0, 0.30), "cyl", (0, 0, 0.125), (0.04, 0.25), 1.5, "orange"),
    ("wrist_1_link", "forearm_link", (0, 0, 0.25), "cyl", (0, 0, 0.04), (0.035, 0.08), 0.6, "grey"),
    ("wrist_2_link", "wrist_1_link", (0, 0, 0.08), "cyl", (0, 0, 0.035), (0.03, 0.07), 0.5, "grey"),
    ("tool_link", "wrist_2_link", (0, 0, 0.07), "box", (0, 0, 0.03), (0.05, 0.05, 0.06), 0.3, "grey"),
    ("gripper_link", "tool_link", (0, 0, 0.06), "box", (0, 0, 0.015), (0.08, 0.05, 0.03), 0.2, "grey"),
]

# joint_name, axis, lower, upper, effort, velocity, damping
JOINTS = [
    ("shoulder_pan_joint", "0 0 1", -3.14, 3.14, 150, 2.0, 0.7),
    ("elbow_pitch_joint", "0 1 0", -2.00, 2.00, 150, 2.0, 0.7),
    ("forearm_roll_joint", "0 0 1", -3.14, 3.14, 80, 2.5, 0.4),
    ("wrist_1_joint", "0 1 0", -2.50, 2.50, 40, 3.0, 0.3),
    ("wrist_2_joint", "0 0 1", -2.50, 2.50, 30, 3.0, 0.3),
    ("wrist_3_joint", "0 0 1", -3.14, 3.14, 20, 3.5, 0.2),
]

JOINT_NAMES = [j[0] for j in JOINTS]


def geom_xml(kind, size, indent="      "):
    if kind == "box":
        s = " ".join(f"{v:.4f}" for v in size)
        return f'{indent}<geometry><box size="{s}"/></geometry>'
    r, l = size
    return f'{indent}<geometry><cylinder radius="{r}" length="{l}"/></geometry>'


def link_xml(name, kind, origin, size, mass, material):
    o = " ".join(f"{v:.4f}" for v in origin)
    # box inertia approximated as a solid cuboid; cylinder as a solid cylinder
    if kind == "box":
        x, y, z = size
        ixx = (mass / 12.0) * (y * y + z * z)
        iyy = (mass / 12.0) * (x * x + z * z)
        izz = (mass / 12.0) * (x * x + y * y)
    else:
        r, l = size
        ixx = iyy = (mass / 12.0) * (3 * r * r + l * l)
        izz = 0.5 * mass * r * r
    return f"""  <link name="{name}">
    <visual>
      <origin xyz="{o}" rpy="0 0 0"/>
{geom_xml(kind, size)}
      <material name="{material}"/>
    </visual>
    <collision>
      <origin xyz="{o}" rpy="0 0 0"/>
{geom_xml(kind, size)}
    </collision>
    <inertial>
      <origin xyz="{o}" rpy="0 0 0"/>
      <mass value="{mass}"/>
      <inertia ixx="{ixx:.6f}" ixy="0" ixz="0" iyy="{iyy:.6f}" iyz="0" izz="{izz:.6f}"/>
    </inertial>
  </link>
"""


def build():
    parts = ['<?xml version="1.0"?>',
             '<!-- Procedural 6-DOF arm. Generated by tools/gen_urdf.py. -->',
             '<robot name="demo_arm">',
             '  <material name="grey"><color rgba="0.55 0.57 0.60 1.0"/></material>',
             '  <material name="orange"><color rgba="0.90 0.45 0.10 1.0"/></material>',
             link_xml("base_link", "box", (0, 0, 0.05), (0.30, 0.30, 0.10), 4.0, "grey")]

    for idx, (name, parent, org, kind, vorigin, size, mass, mat) in enumerate(SEGMENTS):
        if idx >= len(JOINTS):
            break  # gripper_link is driven by the prismatic joint added below
        jn, axis, lo, hi, eff, vel, damp = JOINTS[idx]
        o = " ".join(f"{v:.4f}" for v in org)
        parts.append(f"""  <joint name="{jn}" type="revolute">
    <parent link="{parent}"/>
    <child link="{name}"/>
    <origin xyz="{o}" rpy="0 0 0"/>
    <axis xyz="{axis}"/>
    <limit lower="{lo}" upper="{hi}" effort="{eff}" velocity="{vel}"/>
    <dynamics damping="{damp}" friction="0.05"/>
  </joint>
""")
        parts.append(link_xml(name, kind, vorigin, size, mass, mat))

    # gripper: prismatic joint + its link (SEGMENTS[-1])
    gname, gparent, gorigin, gkind, gvorigin, gsize, gmass, gmat = SEGMENTS[-1]
    parts.append("""  <joint name="gripper_joint" type="prismatic">
    <parent link="tool_link"/>
    <child link="gripper_link"/>
    <origin xyz="0 0 0.06" rpy="0 0 0"/>
    <axis xyz="1 0 0"/>
    <limit lower="0.0" upper="0.04" effort="20" velocity="0.5"/>
    <dynamics damping="1.0"/>
  </joint>
""")
    parts.append(link_xml(gname, gkind, gvorigin, gsize, gmass, gmat))
    parts.append("</robot>\n")
    return "\n".join(parts)


if __name__ == "__main__":
    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    with open(OUT, "w") as fh:
        fh.write(build())
    print(f"wrote {os.path.abspath(OUT)}")