"""Copy the project from the Windows editor tree into the WSL project.

Run this instead of shell-level cp/tar/sed chains: doing the copy and the
CRLF fix in Python avoids the shell-quoting trap where "\\r" is treated as
the literal letter 'r' and every 'r' in every file gets deleted.

    python3 ws/tools/sync_to_wsl.py
"""
import os
import shutil
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
# ws/tools/ -> ws/ -> project root
SRC = os.environ.get("ARMWEB_SRC") or os.path.abspath(
    os.path.join(HERE, "..", ".."))
DST = os.environ.get("ARMWEB_WSL", "/home/thiag/armweb")

sys.path.insert(0, HERE)
from fix_line_endings import normalise  # noqa: E402

TOP_FILES = ["Dockerfile", "docker-compose.yml", ".env", "Makefile", "README.md"]
TREES = ["ws", "scripts", "web"]
SKIP_DIRS = {"install", "build", "log", "node_modules", ".git", "__pycache__"}
# Generated by the test scripts; they are rebuilt on demand and may be
# root-owned inside the container, which would break the copy.
SKIP_FILES = {"identity.dae", "nested.dae", "_rt_test.glb"}

# Signatures of the 'r'-stripping corruption, so we never ship it silently.
# Assembled at runtime to avoid this file matching its own check.
_R = "r"
CORRUPTION = [
    "http.seve" + _R,          # http.server
    "thee.js",                 # three.js
    "scipts",                  # scripts
    "viewe.html",              # viewer.html
    "impot ",                  # import
    "libray",                  # library
    "pytho3",                  # python3
]


def copy_file(rel):
    src = os.path.join(SRC, rel)
    dst = os.path.join(DST, rel)
    if not os.path.isfile(src):
        return False
    os.makedirs(os.path.dirname(dst), exist_ok=True)
    shutil.copyfile(src, dst)
    return True


def copy_tree(name):
    src_root = os.path.join(SRC, name)
    if not os.path.isdir(src_root):
        return 0
    count = 0
    for root, dirs, files in os.walk(src_root):
        dirs[:] = [d for d in dirs if d not in SKIP_DIRS]
        rel_root = os.path.relpath(root, SRC)
        for fn in files:
            if fn in SKIP_FILES:
                continue
            src = os.path.join(root, fn)
            dst = os.path.join(DST, rel_root, fn)
            os.makedirs(os.path.dirname(dst), exist_ok=True)
            # A root-owned leftover from a container build must not abort the
            # whole sync; drop what we cannot overwrite and say so.
            try:
                shutil.copyfile(src, dst)
                count += 1
            except PermissionError:
                print(f"    skip (not writable): {rel_root}/{fn}")
    return count


def scan_for_corruption():
    """Return (path, signature) for any file with r-stripping damage.

    This file necessarily contains the signatures it searches for, so it is
    excluded from its own scan.
    """
    # Compare by name: this script runs from the Windows source tree but scans
    # the WSL copy, so __file__ and the paths being checked never match.
    my_name = os.path.basename(__file__)
    bad = []
    for top in TOP_FILES + [os.path.join("ws", "tools"),
                            os.path.join("ws", "src"),
                            "scripts", "web"]:
        p = os.path.join(DST, top)
        paths = []
        if os.path.isfile(p):
            paths = [p]
        elif os.path.isdir(p):
            for root, dirs, files in os.walk(p):
                dirs[:] = [d for d in dirs if d not in SKIP_DIRS]
                paths += [os.path.join(root, f) for f in files]
        for path in paths:
            if os.path.basename(path) == my_name:
                continue
            try:
                with open(path, "rb") as fh:
                    blob = fh.read()
            except OSError:
                continue
            # Only text files can be corrupted this way.
            if b"\x00" in blob[:2048]:
                continue
            for sig in CORRUPTION:
                if sig.encode() in blob:
                    bad.append((path, sig))
                    break
    return bad


def main():
    if not os.path.isdir(DST):
        print(f"destination not found: {DST}")
        print("set ARMWEB_WSL to the project path inside WSL")
        return 1
    print(f"src: {SRC}")
    print(f"dst: {DST}")

    for f in TOP_FILES:
        if copy_file(f):
            print(f"  file {f}")

    total = 0
    for t in TREES:
        n = copy_tree(t)
        total += n
        print(f"  tree {t}: {n} files")
    print(f"copied {total} files in trees")

    # Normalise line endings on everything we just wrote.
    changed = []
    for top in TOP_FILES + TREES:
        p = os.path.join(DST, top)
        targets = [p] if os.path.isfile(p) else (
            [os.path.join(r, f)
             for r, d, fs in os.walk(p)
             for f in fs] if os.path.isdir(p) else [])
        for t in targets:
            try:
                if normalise(t):
                    changed.append(t)
            except OSError:
                pass
    print(f"normalised line endings in {len(changed)} files")

    bad = scan_for_corruption()
    if bad:
        print("")
        print("FAIL: r-stripping corruption detected:")
        for path, sig in bad[:20]:
            print(f"  {path}  ({sig!r})")
        return 1

    mk = os.path.join(DST, "Makefile")
    if os.path.isfile(mk):
        with open(mk, "r", encoding="utf-8", errors="replace") as fh:
            if "http.server 8080" in fh.read():
                print("Makefile web target intact")
            else:
                print("WARNING: Makefile web target still wrong")

    print("")
    print("sync OK")
    return 0


if __name__ == "__main__":
    sys.exit(main())